version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"
    restart: always
